openai_api_key = "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"
email_user = "spkincident@gmail.com"
email_password = "12345678A!"
