openai_api_key = "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"
email_user = "spkincident@gmail.com"
email_password = "12345678A!"
