openai_api_key = "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"
email_user = "spkincident@gmail.com"
email_password = "12345678A!"
