openai_api_key = "sk-proj-33SYhgrAjeGh3Ph3g22HEkNfXR9PMvf4raelg2osKpqRtPF9iZ9AaAP3tZb5TyOuL9lCuJe2XT3BlbkFJCf9__CRhxwvq0CxwfFF9XLRrY6cQX11pseWbR8JWeOIIkizMmbJxdyRSJGQsx-VPyybuuddcIA"
email_user = "spkincident@gmail.com"
email_password = "12345678A!"
